### ISSUE TITLE
save color value as hex

### ISSUE THREAD

**Issue by YokujinKaze** [MichaelHillcox/XRay-Mod#142]
currently you save the color value as a sum of a 6 hexdecimal value (0-16777215), the conversion is pretty annoying if you want to change the value in the file

why not save them as hex? (000000-FFFFFF)

(if you havent changed that already)

**Comment by MichaelHillcox** [comment]
Just change them in game using the RGB editor. I could modify it but it would require more changes to the Json for not much reason. If i you want to PR it in then please feel free but I don’t have time to make this change sorry.

**Comment by Artoria2e5** [comment]
JSON is a bit of a headache on this since you can't just slip in a 0x sort of hex number there (no change to decode code!), but need to actually make it serialize into a string field (actually changing the data structure :( ). If someone else wants to play with the `TypeAdapter` thing, go for it.

(Was thinking about some other color thing, well.)
