### ISSUE TITLE
Crashing on FTB Beyond 1.10.2 with XRay 1.3.0

### ISSUE THREAD

**Issue by Hexogenx** [MichaelHillcox/XRay-Mod#16]
Opening the GUI crashes, here's the log (pastebin limits to 512kb, so I used something else):

https://zerobin.net/?7e028a7deaf23285#CwfOUi4fi36Q9Lgc/kTHrZalAbGzRWDmpV/iOBPDTmg=

**Comment by MichaelHillcox** [comment]
This is an issue I know about and I'm working towards a solid fix now. This is due to the difference between how some functionality works in 1.12 compared to 1.10.2. A fix should be release very soon :)

**Comment by Hexogenx** [comment]
The tempfix leads to horrible Tick lag after 20 seconds of running that reoccurs every 5 seconds. I tried looking at the code to see if I can fix it myself but I'm not knowledgeable enough :(

**Comment by MichaelHillcox** [comment]
I've not yet released the temp fix? I'd assume you've build the mod yourself although I've done the same thing and ran it on a FTB pack myself and it's been fine. It wouldn't be able to create tick lag due to the fact that the issue is coming from Gui and not the actual rendering code of which does unfortuantly have an impact on lower spec pcs and higher spec but it's less noticable.

**Comment by Hexogenx** [comment]
Yeah I've built it myself with gradle ^^ I was under the assumption that the commit you made was the temp fix for the problem but not enough for you to release it as a public build, so I went ahead of myself and used it already. I just tried to reproduce the lag issue but I couldnt, maybe it's because I've rebuilt the .jar and maybe had some issues the first time I've built it. My bad :)

**Comment by MichaelHillcox** [comment]
I've fixed this now. Thanks for pointing it out because I've been able to fix a load of other issues too 💓
There should be a new release very soon on curse and I always release on github first :)
