### ISSUE TITLE
Xray for Lava? 

### ISSUE THREAD

**Issue by Poetic-Abortionist** [MichaelHillcox/XRay-Mod#30]
This is a suggestion rather an issue.

**Comment by SpeTheof** [comment]
yeah that would be great actually, and there is no suggestions tab so I guess it's fine, like i did

**Comment by MichaelHillcox** [comment]
Suggesting like this is more than fine with me :heart: I like your suggested but I think the better option here would be to give the player a light emitter so that they don't need to place touches while the mod is running. I think this would be a more elegant solution that telling the player when to look out for lava. 

I could scan a small area around the player and maybe highlight lava red? This might be another subtle idea?

Currently we have an issue with scanning blocks and CPU usage which you can see here #33 if you are interested.

**Comment by emperor06** [comment]
I've been displaying lava since 1.7.10 without any problem. You just have to set it in the config.
Block id is 11, meta is 0.
I think back in the days, you could enter the block id directly in the mod interface.
Adding it as default "ore" is a good idea.

Here's an example if you want to manually add lava to xray.conf
>lava {
>  I:blue=0
>  B:enabled=true
>  I:green=100
>  I:id=11
>  I:meta=0
>  S:name=Lava
>  I:red=250
>}

And here's the result in the world

![lava](https://user-images.githubusercontent.com/9116243/37923792-59bad458-3130-11e8-91e5-5506c997177e.jpg)

**Comment by MichaelHillcox** [comment]
Yeah, I think I'm gunna close this because it's more than possible to do
