### ISSUE TITLE
Newest version doesn't update xray after mining block

### ISSUE THREAD

**Issue by Geekerandy** [MichaelHillcox/XRay-Mod#42]
I mine the block xray has targeted and moving around doesn't refresh the xray search, like it did in the past. I have to reload the xray itself with the hotkey. Is this intended?

UPDATE: Okay, it does update, but you have to walk around a bit more than intended.
Then again, could I get it to update every time I walk even a block?
2nd update: Okay, it seems to update very inconsistently, where I can walk either very short or long distances before updating.

**Comment by MichaelHillcox** [comment]
Hi @Geekerandy 
Thanks for letting me know about this. I've had it on the todo list of things to fix but hadn't noticed that the issue was getting worse. I'll be sure to get this sorted out. I think @emperor06 has already started a branch to try and solve the bigger issue that this issue is related to. You can see the progress is #43

**Comment by emperor06** [comment]
Updated and solved on last commit about threads. Breaking or adding blocks is now processed directly, without having to rescan the whole area.

**Comment by MichaelHillcox** [comment]
This can be closed now in prep for the next release :D

**Comment by MichaelHillcox** [comment]
Solved as of #50
