### ISSUE TITLE
Suggestion: Add a palette of colors derived from the block texture to pick a color for a block.

### ISSUE THREAD

**Issue by calloatti** [MichaelHillcox/XRay-Mod#47]
Right now when selecting a new block, you have to select the wire color using RGB values.

Maybe you could also implement a palette derived from the block texture to make it easier to pick a color.

For example for a chest:

![image](https://user-images.githubusercontent.com/12817862/37917489-f324d2e2-30f4-11e8-8379-cec6a44e82d6.png)

Others blocks:

![image](https://user-images.githubusercontent.com/12817862/37917562-2076822c-30f5-11e8-812e-dcb0e9cfaa0c.png)

![image](https://user-images.githubusercontent.com/12817862/37917599-38c000c4-30f5-11e8-88dc-fe682b4c24ee.png)

References:

https://github.com/lokesh/color-thief

http://lokeshdhakar.com/projects/color-thief/

https://github.com/SvenWoltmann/color-thief-java

**Comment by MichaelHillcox** [comment]
Thats a lovely idea. I think can add that pretty easily with a toggle button to switch between RGB and a palette. I've also wanted to remove the current rgb selector and add one more in tune with modern rgb selectors https://i.imgur.com/CYzpqIr.png

**Comment by calloatti** [comment]
Yes, the rgb selectors suck too, did not want to be too mean so I did not say anything about them. 

Re color palettes, discrete ones are much better for the end user than continuous ones. Less options but a lot easier to visualize and pick a color.

After all you don't need in this case 1000s of colors, just a bunch. Maybe something like this:

![image](https://user-images.githubusercontent.com/12817862/37920560-94845d62-30fd-11e8-803b-37719deb4a5e.png)

But only the bottom part, the rest makes it too complicated to this. That is a color picker I created ages ago for UI design.

Make the step larger than 5 (maybe 10) to the vertical axis (Luminance), and more than 10 for the Hue (horizontal) and a fixed Saturation (around 70-80) you are golden.

This is an HSL color palette.

**Comment by MichaelHillcox** [comment]
I think a simple rgb selector like I showed will be best, there is a lot of options there are would be more confusing than if it was one like mine or that pre-existing on. The idea of it is to make it simpler to understand and easy to pick a color, I feel like a lot of people don't know how the RGB sliders work due to the fact that you need to know which colours mix to make the desired colour. I think the original idea of finding primary colours from the blocks texture will be the besy way of doing it :D along with a toggle to show the rgb selector

**Comment by MichaelHillcox** [comment]
I'll come back to this one
