### ISSUE TITLE
Some blocks don't show up once added

### ISSUE THREAD

**Issue by AriinPHD** [MichaelHillcox/XRay-Mod#5]
Some blocks just won't show up when added. The add-feature does not support name:id (i.e. minecraft:gold_ore) as it only errors with an old error message stating "[ï¿%aFgt XRayï¿%t] minecraft:gold_ore contains data other than numbers and the colon. Failed to add."

This seems to be the case for a lot of blocks from mods such as Iskallium Reactors (Iskallium Ore) and Nether Core which adds a variety of ores all using the same IDs, sometimes separated by a forward slash "/". For example: 6636/7

**Comment by MichaelHillcox** [comment]
I've not added support for meta. Mainly because I have no idea on how I would go about it. I'm not really a minecraft modder.... I just know java kinda. Wanted to keep the mod alive. It works with all the basic modname:blockname structure but doesn't work with anything more complex than that. Sorry about that. 

Can you confirm what version you're using?

**Comment by AriinPHD** [comment]
>>I've not added support for meta [...]I'm not really a minecraft modder
Alright. Thanks for the quick reply! No worries. Good luck with that, too! :)

>>Can you confirm what version you're using?
1.1.01 on forge 12.18.3.2281

**Comment by MichaelHillcox** [comment]
@AriinPHD Right, so I've actually replied to this incorrectly. I was under the assumption that I had added support for MODNAME:BLOCKNAME but apparently I havent. The issue you where having is that you needed to use `6636:7` for the block that you wanted. Hope this helps. If I'm still wrong then just open the ticket back up <3
