### ISSUE TITLE
Not an issue, just a suggestion..

### ISSUE THREAD

**Issue by GeooKL** [MichaelHillcox/XRay-Mod#57]
I love the GUI of this mod, and just how easy it is to add blocks to xray.. my only issue is a personal  gripe... some may agree some may not,   I am not a huge fan of how xray works, I completely understand. why you'd do it this way, I really do,, but some of us enjoy the old way..... so you can see the whole blocks and not just an outline... I found  this other xray mod what allows you to see all of the blocks rather than just an outline.. just not as good as a GUI...

so my question is, could you allow a feature that caters to both kinds of people? even a config to switch back to legacy xray.. or something. and keeps the GUI the same.

**Comment by MichaelHillcox** [comment]
I'd assume you are refering to making all other blocks see through?

**Comment by GeooKL** [comment]
Hi, thanks for the reply, .. what I meant was, make the blocks solid... and you use the current GUI to select what blocks you want to see or not to see... let me try upload an image to show you what I mean.. 


https://gyazo.com/3ea884a79070e8060d678a5545872433


or you could add a feature to choose the transparency.. to solid to slightly see through  I am not saying get rid of how xray works now, just saying add more than one method.

**Comment by MichaelHillcox** [comment]
I personally took this project on because of how it differs from normal xrays, I hate walking into blocks all the time and not being able to see where I'm going, that being said, I can look into how complicated it might be to make a mod like you have described. If it is relatively simple and it wouldn't impact the current functionality of the mod then I have no issue with it being implemented.

**Comment by GeooKL** [comment]
As I said, I get it, walking into blocks is annoying for some people, and that's a good way to combat it., but like I said people have different things they prefer.

**Comment by MichaelHillcox** [comment]
Due to the complexity of this mod vs one that functions in the way you've described I think it would be less than an ideal situation to have such a system implemented into this project although I may create a "Legacy" / "Classic" version of the mod which will do as you've described but with all the lovely gui and functionality 👍
