### ISSUE TITLE
Minecraft crashes on Z

### ISSUE THREAD

**Issue by Jaeiya** [MichaelHillcox/XRay-Mod#76]
**Describe the bug**
Going into a new world, when I hit the Z key to bring up the GUI, it crashes minecraft instantly.

**To Reproduce**
1. Load into a new world
2. Tap Z

**Expected behavior**
The GUI to appear.

**Crash Log**
[crash-2018-07-24_15.18.52-client.txt](https://github.com/MichaelHillcox/XRay-Mod/files/2225673/crash-2018-07-24_15.18.52-client.txt)

**Minecraft Enviorment**
 - Minecraft Version: 1.12.2
 - XRay Mod Version: 1.12.2-1.5.0
 - Forge Version: 14.23.4.2736

**Comment by Aedaeum** [comment]
It was not a fresh install, but it was a newly generated world. The odd thing is, I originally installed this mod to check the ore distributions before making the world official.... at the time I was doing this it worked great.

A few days ago I wanted to tweak a few things so I created a test world and then got this crash out of no where.... So it did work before...

I'm loading up the game now with your config to test.

**Comment by Aedaeum** [comment]
It's your lucky day though, while traversing in spectator mode through the ground to check out the ore distributions, XRay crashed again :laughing: 

[crash-2018-07-25_13.44.05-client.txt](https://github.com/MichaelHillcox/XRay-Mod/files/2229490/crash-2018-07-25_13.44.05-client.txt)

**Comment by MichaelHillcox** [comment]
Thanks for all this, I'll be able to get a lot sorted because of these.

**Comment by Aedaeum** [comment]
Glad I could help :smile: 

I should also add that before the original crash, I had uninstalled XRay once I decided to make my world "official". So when it stopped working, that was on a re-install (using the Twitch app). I use the Twitch app exclusively to update/install/uninstall my mods.

I'm a programmer myself so I know every bit of information (seemingly pointless or not) can be helpful.

**Comment by MichaelHillcox** [comment]
If you know java then feel free to fix the issue, haha. Contribuations are always welcome. I've been aware of the issues for a little while now but I've not had the time to update the mod. I've started a v2 rewrite of the system because as it stands there is a lot of code debt from the very first version. 

They are all on my todo list but I think I'm going to be pushing a config fix very soon.

**Comment by Aedaeum** [comment]
Haha, if it was written in JavaScript then I might take a stab at it, but Java isn't a language I've made a part of my repertoire. Good luck though; this is a great mod for checking ore distribution, might I say, invaluable in that regard.

**Comment by MichaelHillcox** [comment]
I'm glad it has served an alternative use apart from being used to cheat :P I personally only made it because I have very little time in my days to play games and when I do I don't want to spend 5 hours mining for ores. So instead I use this mod as a helping tool. I'm sure others use in a much more hacky way. Thanks for your nice comments though ❤️

**Comment by MichaelHillcox** [comment]
If you have any suggestions for the mod then be sure to make a new issue with them. I consider all feedback I recieve

**Comment by Aedaeum** [comment]
Will do. It's nice to see a dev passionate about their project :smile:

As far as using it as a tool to quickly gather resources; what I've done to make things a little easier, is actually adjust the default world gen using `cofh world`. I've basically adjusted it, so that the harder to find ores, spawn in a limited area so I know exactly which Y-level to strip mine, to get a bunch of it.

Still a little grindy, but it's much quicker than vanilla for sure.

**Comment by MichaelHillcox** [comment]
Should be fixed as of https://github.com/MichaelHillcox/XRay-Mod/commit/f893ffc202dd50475ddaefd32fa4ddd0f9261727 with #85
